import { GoogleGenAI, Type } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const HUMANIZER_PROMPT = `Rewrite the following text to make it sound more natural, engaging, and human-like. 
Remove any robotic or overly formal tone. The goal is to produce content that is clear, relatable, and feels authentically written by a person. 
Focus on natural language, empathy, simplicity, and cultural awareness. 
{VARIETY_INSTRUCTION}
Do not add any introductory or concluding phrases like 'Here is the rewritten text:' or 'I have rewritten the text as requested.'. Just provide the rewritten text directly.

Original Text:
---
{TEXT_INPUT}
---
Rewritten Text:
`;

export type WritingVariety = 'default' | 'varied' | 'concise';

export async function humanizeText(text: string, variety: WritingVariety = 'default'): Promise<string> {
    if (!text) {
        return "";
    }

    let varietyInstruction = '';
    if (variety === 'varied') {
        varietyInstruction = 'Pay special attention to varying sentence length and structure to create a dynamic reading experience. Mix short, punchy sentences with longer, more descriptive ones.';
    } else if (variety === 'concise') {
        varietyInstruction = 'Focus on making the text clear and direct. Use shorter sentences and simpler language where possible, without losing the core meaning.';
    }

    try {
        const fullPrompt = HUMANIZER_PROMPT
            .replace('{VARIETY_INSTRUCTION}', varietyInstruction)
            .replace('{TEXT_INPUT}', text);
            
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: fullPrompt
        });
        
        if (response.text) {
            return response.text.trim();
        } else {
            throw new Error("No text was generated.");
        }
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to communicate with the AI service.");
    }
}

const DETECTOR_PROMPT = `
You are an expert AI content detector with a deep understanding of linguistic patterns, statistical analysis, and semantic structures.
Analyze the following text based on several critical factors to determine the likelihood that it was generated by an AI.

For the text provided, perform the following analysis:
1.  **Perplexity Analysis**: Measure the predictability of the text. Low perplexity suggests predictable, AI-like patterns.
2.  **Burstiness Analysis**: Evaluate the variation in sentence length and structure. A human-like text often has a high standard deviation in sentence length, mixing short, emphatic sentences with longer, more complex ones. AI text is often more uniform. Comment specifically on this mix and variation.
3.  **Sentence Structure & Style**: Look for repetitive phrasing, uniform tone, and overly complex or simplistic sentence structures that are characteristic of AI models.
4.  **Semantic Consistency**: Check for logical flow and subtle inconsistencies in meaning. While AIs are good at consistency, they can sometimes lack the nuanced, contextual understanding of a human writer.
5.  **Statistical Pattern Analysis**: Examine n-gram frequency, sentence length distribution, and punctuation habits to detect machine-like statistical patterns.
6.  **AI Watermark Detection**: Scan for subtle, repeating, non-linguistic patterns or artifacts in the text that could act as hidden watermarks or model identifiers.
7.  **Lexical Originality**: Evaluate the uniqueness of vocabulary and phrasing. Does the text rely on common words and clichés, or does it exhibit a more creative and diverse lexicon?
8.  **Emotional Tone Analysis**: Assess the authenticity and nuance of emotional expression. Human writing often contains subtle emotional cues, whereas AI text can be emotionally flat or generic.

Based on your analysis, provide a detailed breakdown in a JSON object. The scores should be from 0 to 100, where 100 indicates a very high likelihood of being AI-generated for that specific metric. Also, provide a brief, one-sentence explanation for each score. Finally, provide an overall score and explanation.

Do not analyze for external metadata.

Respond ONLY with a valid JSON object following this schema:
{
  "overallScore": number,
  "overallExplanation": string,
  "analysis": {
    "perplexity": { "score": number, "explanation": string },
    "burstiness": { "score": number, "explanation": string },
    "sentenceStructure": { "score": number, "explanation": string },
    "semanticConsistency": { "score": number, "explanation": string },
    "statisticalAnalysis": { "score": number, "explanation": string },
    "watermarkDetection": { "score": number, "explanation": string },
    "lexicalOriginality": { "score": number, "explanation": string },
    "emotionalTone": { "score": number, "explanation": string }
  }
}

Text to analyze:
---
{TEXT_INPUT}
---
`;

export interface AnalysisMetric {
    score: number;
    explanation: string;
}

export interface AiDetectionResult {
    overallScore: number;
    overallExplanation: string;
    analysis: {
        perplexity: AnalysisMetric;
        burstiness: AnalysisMetric;
        sentenceStructure: AnalysisMetric;
        semanticConsistency: AnalysisMetric;
        statisticalAnalysis: AnalysisMetric;
        watermarkDetection: AnalysisMetric;
        lexicalOriginality: AnalysisMetric;
        emotionalTone: AnalysisMetric;
    };
}

const metricSchema = {
    type: Type.OBJECT,
    properties: {
        score: { type: Type.NUMBER, description: "The AI-generation likelihood score for this metric (0-100)" },
        explanation: { type: Type.STRING, description: "A brief explanation of the score for this metric" },
    },
    required: ["score", "explanation"],
};

export async function detectAiText(text: string): Promise<AiDetectionResult> {
    if (!text.trim()) {
        throw new Error("Input text cannot be empty.");
    }

    try {
        const fullPrompt = DETECTOR_PROMPT.replace('{TEXT_INPUT}', text);
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: fullPrompt,
            config: {
                temperature: 0,
                topK: 1,
                seed: 42,
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        overallScore: { type: Type.NUMBER, description: "The overall AI-generation likelihood score (0-100)" },
                        overallExplanation: { type: Type.STRING, description: "A brief explanation of the overall score" },
                        analysis: {
                            type: Type.OBJECT,
                            properties: {
                                perplexity: metricSchema,
                                burstiness: metricSchema,
                                sentenceStructure: metricSchema,
                                semanticConsistency: metricSchema,
                                statisticalAnalysis: metricSchema,
                                watermarkDetection: metricSchema,
                                lexicalOriginality: metricSchema,
                                emotionalTone: metricSchema,
                            },
                            required: ["perplexity", "burstiness", "sentenceStructure", "semanticConsistency", "statisticalAnalysis", "watermarkDetection", "lexicalOriginality", "emotionalTone"],
                        }
                    },
                    required: ["overallScore", "overallExplanation", "analysis"],
                },
            },
        });

        if (response.text) {
            const result = JSON.parse(response.text) as AiDetectionResult;
            // Basic validation to ensure the structure is as expected
            if (typeof result.overallScore === 'number' && result.analysis?.lexicalOriginality?.score !== undefined) {
                return result;
            }
        }
        throw new Error("Invalid response format from AI service.");

    } catch (error) {
        console.error("Error calling Gemini API for AI detection:", error);
        if (error instanceof SyntaxError) {
             throw new Error("Failed to parse AI response. The service returned an unexpected format.");
        }
        throw new Error("Failed to communicate with the AI service for detection.");
    }
}